### ISSUE TITLE
Feat/Timer 이슈 발생 - 시간 기록 API

### ISSUE THREAD

**Issue by seonghoo1217** [Mogakco-web/BE-Mogakco#28]
## 🚀 이슈 발생
- 현재 타이머 로직의 경우 **타이머 생성 날짜**인 `timerCreDay`와 MemberEntity인 `MemberSocial` 클래스를 `Spring Data JPA`를 통해 `Timer Entity` 를 반환 받는다.
- 하지만 이 때 자정이 넘어갈 경우 RDB의 저장 기준이 모호해짐
  - 예를 들어, 3월 21일 오후 10시에 공부를 시작할 경우 Timer Table에 `TimerCreDay`필드에는 `2023-03-21`의 값이 들어간다.
  - 이 후 3월 21일 자정을 넘어 22일 2시쯤 공부를 마무리 할 경우 새로운 `DB 컬럼`을 생성해야 하는지 또는 이전 값에 덧 붙여야하는지의 이슈
  - 클라이언트 측에서는 현재 날짜를 **필터링**하여 Server로 전송하기에 **무조건**적으로 새로운 컬럼이 생성 됨
  - 또한 클라이언트 측에서의 화면 처리도 자정이 지날경우 갑자기 0초 부터 초기화 해야 하는 이슈 발생

## 현재 로직
1. 클라이언트가 Timer Page 입장 시 클라이언트에서 해당 날짜에 맞는 `recodeInitialize` 메소드를 실행시켜, DB를 초기화한다.
2. 클라이언트가 Timer를 사용 후 정지 버튼을 누르게 된다면, 해당 시점에 DB로 API를 전송한다.
3. 서버는 해당 Request를 `Update 처리`하는 로직을 구현하여 진행

## 이슈 1과 2로 분리
- **이슈 1**을 이전 날짜 정보에 연속하여 데이터를 Update 시키는 방법으로 정의
- **이슈 2**을 새로운 DB 컬럼을 생성하는 방법으로 정의

**이슈 1 관점**
- 자원의 재사용성이 증가
- 사용자에게 연속된 기록을 제공함으로서 성취감 제공
- 유지보수 입장에서의 편리성
- 가장 큰 문제점인 날짜 정보를 저장하여 이전 사용기록과 동일화 시키는 것 , 또한 해당 날짜의 추후와 분리 시키는 것

**이슈 2 관점**
- 기술적 문제로 인한 선택
  - 하지만 이 또한 문제, 예를 들어 21일 오후 11시 55분에 공부를 시작하여, 22일 오전 2시에 정지를 하게 된다면 DB에는 서로 다르게 저장되지만, 클라이언트에서 시간초를 처음부터 0초로 다시 표기하는 문제점 발생

## 관련 코멘트 및 이슈 토론 진행 - 23.03.21
- **이슈 토론 참여자**  : @seonghoo1217 @Siby1lA  

## 해결 및 대처방안 목록
- `일시정지` 버튼을 사용하여 처리(완벽한 처리 방법 X)

**Comment by seonghoo1217** [comment]
@Siby1lA 혹시라도, 프론트에서 `/api/v1/timer/todayInfo`를 통하여 응답받는 Response에 포함된, `timerCreDay`를 별도로 저장 및 추후 API 요청 시 처리할 수 있는 방법이 있을까요?

**Comment by Siby1lA** [comment]
@seonghoo1217
`/api/v1/timer/todayInfo` 에서 받은 응답값은 별도로 저장하고 추후에 서버에 요청할때도 사용할 데이터가 아니어서 걱정하지 않으셔도 됩니다!
