### ISSUE TITLE
Feat/Timer - 시간 저장 로직 변경

### ISSUE THREAD

**Issue by seonghoo1217** [Mogakco-web/BE-Mogakco#29]
## 🚀 Issue (Trouble)
- 현재 Timer 기능은 #28 이슈에서 지칭하는 `이슈 1(연속모드)`을 구현하기 위해 일시 정지 로직을 통해 시간을 Client 측에 저장하다가 DB저장 시점에 최초로 API를 호출하는 기능
- 하지만, **네트워크 장애** 또는 **트래픽 이슈**,**새로고침이나 여타 클라이언트에서 발생하는 초기화 이슈**를 만나게 될 경우 일시 정지 로직 만을 통해 저장되어 있던 시간이 증발하는 문제 발생
- 이를 해결하기 위한 방법을 두 가지 정도로 선정

## Way to Trouble Shooting
1. Redis와 같은 `Cache DB`를 운영하여 일시 정지 시에도 서버로 API를 호출하여 임시저장
2. 일정시간 마다 Client에서 API를 호출하는 방법

## Contributors
- 이슈 논의 참여자 : @seonghoo1217 @Siby1lA

**Comment by Siby1lA** [comment]
페이지 이탈시, 현재까지 쌓인 시간을 서버에게 저장할 수 있도록 보내는 로직을 한번 짜보겠습니다.
